### ISSUE TITLE
Docs pages

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_zictia_demo#11]
- [x] new design on figma file for docs layout: https://www.figma.com/file/N07USOu1ZyB4cBazzPWiC8/ZICTIA?type=design&node-id=0%3A1&mode=design&t=bvktU6p8LK4fJSTk-1
- [x] make 4 different pages with these exact titles, alsoi change the menu: 
1. Legal Tenders
2. Legal Acts
3. Brochures 
4. Request Form

- [x] all files here zipped to make it easier: 
https://we.tl/t-bvEQ8YUl4l

on the old web, one of file in 'tender' didnt work so its ok only 3 instead of 4.

- [x] when link clicked, ask user to download/save to local, jus like the old website.

**Comment by sasha-astiadi** [comment]
- [ ] add another document section: CORPORATE ACTs, cons
[Archive 2.zip](https://github.com/threefoldfoundation/www_zictia_demo/files/13687678/Archive.2.zip)

- [ ] Doc 1 title for link: Corporate Acts (ENG)
- [ ] Doc2 title for link:: Corporate Acts (SWAHILI)

**Comment by ehab-hassan** [comment]
done

**Comment by sasha-astiadi** [comment]
thanks ehab! <3
