### ISSUE TITLE
Create contact Page

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldfoundation/www_zictia_demo#12]
for now, let's have it on the FAQ page then when we have the contact page design we can move the component there

**Comment by samaradel** [comment]
implemented on staging 

![image](https://github.com/threefoldfoundation/www_zictia_demo/assets/11662805/20ecc7f1-1ea9-48a2-9b87-b00856365656)

**Comment by sasha-astiadi** [comment]
updated the contact page on figma:

- [ ] apply design as on figma, (just add header n footer,of the FAQ page).

- [ ] for faq page new header n footer, this issue: https://github.com/threefoldfoundation/www_zictia_demo/issues/13

**Comment by samaradel** [comment]
![image](https://github.com/threefoldfoundation/www_zictia_demo/assets/11662805/cc330519-c354-42c1-8601-35458e2aa9b2)

**Comment by sasha-astiadi** [comment]
thank you @samaradel @ehab-hassan
