### ISSUE TITLE
edit order of service

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_zictia_demo#14]
- [x] SERVICE  Page: Reorder cervices as, 

Capacity lease,
 Internet service, 
 Virtual Machine, 
 Co-location, 
 IP-MPLS and  last 
 Private VPN.

- [x] adjust text and bg color of each service as the change...
always blue-white-blue-white or white-blue-white , but not twice white-white or blue-blue bg

**Comment by samaradel** [comment]
done on staging [Our Services](https://zictia.archive.tf/our_services).

**Comment by sasha-astiadi** [comment]
thannk you @ehab-hassan @samaradel :)
