### ISSUE TITLE
create team page

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_zictia_demo#15]
for https://zictia.archive.tf/team_members

- [x] same / similar as threefold template but html
- [x] remove filter
- [x] remove personal page )(when clicked its not going to each persons page, just not clickable at all)
- [x] page title, subtitle, each persons name and job, order: see figma https://www.figma.com/file/N07USOu1ZyB4cBazzPWiC8/ZICTIA?type=design&node-id=1415%3A252&mode=design&t=Lwaqk9ksoj0xHjAe-1
- [x] photos already ordered from 1-14 , clockwise based on figma on this zip:
[zictia_team.zip](https://github.com/threefoldfoundation/www_zictia_demo/files/13728668/zictia_team.zip)

**Comment by samaradel** [comment]
![image](https://github.com/threefoldfoundation/www_zictia_demo/assets/11662805/e61d2e4e-284a-4c90-acc0-b977dc4fb21d)
