### ISSUE TITLE
new corrections

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_zictia_demo#19]
review from zictia side:

1.The team Members
 should appeared and resize as attached in excel sheet also double check name, title and photos as attached
- [x] from what i understand here, he wants us to make photos portrait instead of landscape [see figma](https://www.figma.com/file/N07USOu1ZyB4cBazzPWiC8/ZICTIA?type=design&node-id=1415%3A252&mode=design&t=ZC0eQzmkU4sduedB-1), 

- [x] and please double check the names, according to excel sheet. they gave a newcorrection name form:
[team member (1).xlsx](https://github.com/threefoldfoundation/www_zictia_demo/files/14402006/team.member.1.xlsx)

2. Review "About ZICTIA, MISSION, VISION and other information as attached in word document
- [x] see figma, change the order, first the **message**, then **about**...
- [x] add button '**readmore**' on **new page of message**, 
- [x] add new page to it, to see the **full message of the director**. see figma
- [x] edit the **text 3 sections** of 'about zictia, change it to the one on figma. also **edit the bg color, since the order changed**
- [x] edit all **vision mission text**, see figma

3. Some buttons are still inactive in HOME PAGE,
- [x] please check all buttons

4. Consider to put SMZ Logo on the pages header and ZICTIA logo on the right side (I attached SMZ Logo)
<img width="732" alt="SMZ LOGO (1)" src="https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/86feda35-135e-40c7-ac56-6e33e623e7b0">

- [x] add this logo next to contact button
<img width="1434" alt="Screenshot 2024-02-26 at 11 58 30" src="https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/14897bbb-1210-458e-8b65-8deb4dfe6362">

5.Replace the "site request form" with the attached new one

- [x] [SITE ACCESS FORM.docx](https://github.com/threefoldfoundation/www_zictia_demo/files/14402027/SITE.ACCESS.FORM.docx)

**Comment by sasha-astiadi** [comment]
- [ ] discover -- fiber routes button
- [ ] hide customers review buton but display the comment in full (add more texts) like in figma.
<img width="596" alt="Screenshot 2024-02-27 at 09 59 36" src="https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/525596aa-6529-46d8-8682-8646c421b45b">

- [ ] change button to news
<img width="617" alt="Screenshot 2024-02-27 at 10 01 50" src="https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/c466cfa8-0af3-4d2f-a69d-8946d96a4796">

- [ ] our mgmt goes to https://zictia.archive.tf/organization_structure

- [ ] fix img size 
<img width="572" alt="Screenshot 2024-02-27 at 10 04 04" src="https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/f0ff30d3-edf6-4ca9-ac11-2e14164bc59d">

- [ ] fix typo "General Manager"

**Comment by sasha-astiadi** [comment]
- [ ] fix space between logo aand navbar ?  , make it as figma, maybe make navbar a bit mor centered of page
![Navbar](https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/56fd080e-93e9-4be4-8ef2-f90a42716543)


- [ ] add logo on footer too see figma
<img width="845" alt="Screenshot 2024-02-27 at 10 19 05" src="https://github.com/threefoldfoundation/www_zictia_demo/assets/43240801/dce10902-ea0d-4fd5-b565-5c2f51c46f01">

**Comment by ehab-hassan** [comment]
all done @sasha-astiadi please check
