### ISSUE TITLE
routes page

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_zictia_demo#9]
as seen: https://zictia.go.tz/fiberRoutes.php

- [x] use improved design and texts on figma, all core design (navbar, etc same as other pages).

https://www.figma.com/file/N07USOu1ZyB4cBazzPWiC8/ZICTIA?type=design&node-id=0%3A1&mode=design&t=bvktU6p8LK4fJSTk-1

- [ ] lets try to implement iframe from google earth instead of screenshot:
not sure if will work or not, 

<div style="width: 100%"><iframe width="100%" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=250&amp;hl=en&amp;q=ZICTIA%20Tanzania+(ZICTIA-Head%20Quater)&amp;t=k&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe></div> 

- [ ] mobile responsive

**Comment by sasha-astiadi** [comment]
@ehab-hassan Just saw the demo website, on this, and i just changed few orders on the figma design onfiber routes page.

- [ ] can we do both live map and map, i have edited the figma to do so
- [ ] please build as the new layout and text order on figma for this page, thank you!

**Comment by ehab-hassan** [comment]
@sasha-astiadi check it that what you want because I think they need to show their Fiber Routes on map not the location of the island from Google map
https://zictia.archive.tf/fiberRoutes
